import { Poppins } from "next/font/google";
// import styles from './home.module.scss'
import "./globals.css";
import toast, { Toaster } from 'react-hot-toast';
import ToasterProvider from "@/components/toaste-provider";
// import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AntdRegistry>
          <ToasterProvider />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
